---
fail_fast: false
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply  # Ensure that the configured hooks apply to at least one file in the repository
        always_run: true
      - id: check-useless-excludes  # Ensure that exclude directives apply to any file in the repository
        always_run: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: end-of-file-fixer
        stages:
          - commit
      - id: mixed-line-ending
        args: [--fix=lf]
        stages:
          - commit
      - id: trailing-whitespace
        stages:
          - commit
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        args: [--config=setup.cfg]
        types: [python]
        stages:
          - commit
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        args: [--config-file, setup.cfg]
        types: [python]
        stages:
          - commit
